# This config contains a much more verbose assessment of the code than that defined
# in .golangci.yml and is not suitable as a quality gate in CI.
run:
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true

  timeout: 2m
  skip-dirs-use-default: true

linters-settings:
  goimports:
    local-prefixes: github.com/byatesrae/
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  tagliatelle:
    case:
      rules:
        json: snake
      
linters:
  enable-all: true
  disable:
    - testpackage
    - gci
    - goerr113
