version: "3.5"
services:
  weather-api:
    container_name: weather-api
    image: weather-api
    build: .
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    environment:
      - GOOS=linux
      - GOCACHE=/tmp
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - WEATHERTSTACK_ACCESS_KEY=${WEATHERTSTACK_ACCESS_KEY}
      - PORT=8080
    ports:
        - "8080:8080"
  prometheus:
    container_name: weather-api-prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
