version: "3.5"
services:
  weather-api:
    container_name: weather-api
    image: weather-api
    build:
      context: .
      args:
        BUILD_IMAGE: ${BUILD_IMAGE}
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
        - "8080:8080"
  prometheus:
    container_name: weather-api-prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
