name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, edited ]
    branches:
      - master
  push:
    branches: [ master ]
  
jobs:
  ci-workflow:
    uses: byatesrae/go_build/.github/workflows/ci.yml@master