name: Lint Pull Request

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, edited ]
    branches:
      - master

permissions:
  contents: read
  pull-requests: read
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          args: -c ./.golangci.optional.yml --issues-exit-code=0
          only-new-issues: true
