name: Lint Pull Request

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, edited ]
    branches:
      - master
  
jobs:
  lint-pr-workflow:
    uses: byatesrae/go_build/.github/workflows/lint-pr.yml@master
