name: quality

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, edited ]
    branches:
      - master
  push:
    branches: [ master ]

jobs:
  quality:
    name: quality
    if: ${{ false }}  # disable while testing CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run quality
      run: make quality

    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: 'coverage.html'
